
# Use an official OpenJDK image as the base image
FROM openjdk:17-oracle

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container
COPY Product.jar /app/Product.jar

#COPY ./file.sh /
#RUN chmod 755 /file.sh
#ENTRYPOINT [ "/file.sh" ]
# Specify the command to run the JAR file
CMD ["java", "-jar", "Product.jar"]



#FROM openjdk:17-jdk-alpine
#WORKDIR /app
#COPY target/Product.jar Product.jar
#ENTRYPOINT ["java", "-jar", "Product.jar"]

#docker build -t Product.jar .
#docker run -it Product.jar

#docker run -it --entrypoint /bin/sh Product
#java -jar Product.jar
